import { Forfait } from './forfait';

export const forfaits : Forfait [] = [
    { 
        da:'Miami',
        _id: '',
        destination: 'Miami, Florida',
        villeDepart: 'Toronto',
        hotel: {
            nom: 'Regency Hotel',
            coordonnees: '1000 NW 42nd Ave, Miami, FL 33126, United States',
            nombreEtoiles: 3,
            nombreChambres: 220,
            image: "https://cf.bstatic.com/images/hotel/max1024x768/201/201804557.jpg",
            caracteristiques: [ 'Parking gratuit',
                                "Navette aéroport",
                                "Salles de conférence",
                                "Minibar",
                                "Hôtel non-fumeurs", 
                                'Climatisation',
                                'Wi-Fi gratuit', 
                                'Vue sur la ville'],
        },
        dateDepart:  "2020-05-01",
        dateRetour: "202-05-15",
        prix: 950,
        rabais: 70,
        vedette: true
    },
    {
        da:'Jamaïque',
        _id: '',
        destination: 'Ocho Rios, Jamaïque',
        villeDepart: 'Toronto',
        hotel: {
            nom: 'Beaches',
            coordonnees: " P.O. Box 63, Ocho Rios, St. Ann Jamaica, West Indies",
            nombreEtoiles: 6,
            nombreChambres: 620,
            image: "https://www.caribjournal.com/wp-content/uploads/2019/09/riu-jamaica-resort-1.jpg",
            caracteristiques: [ 'Repas gastronomiques illimités dans 7 restaurants', 
                                'Liqueurs premium illimitées',
                                "2 pisTransferts aéroport aller-retour",
                                "Camp pour enfants avec nounous certifiées",
                                "5 piscines d'eau douce et 2 bains à remous",
                                "WiFi gratuit (dans la chambre et dans tous les espaces communs)", 
                                'Instruction professionnelle pour les sports nautiques',
                                "Salon Xbox Play", 
                                'Petit-déjeuner, déjeuner, dîner et collations à tout moment'],
        },
        dateDepart:  "2021-01-01",
        dateRetour: "2021-01-15",
        prix: 1300,
        rabais: 0,
        vedette: false
    },
    {
        _id: '',
        da:'Canada',
        destination: 'Québec, Canada',
        villeDepart: 'Toronto',
        hotel: {
            nom: 'Fairmont Le Château Frontenac',
            coordonnees: '1 rue des Carrières CITQ No. 040703, Québec City - Quebec, Canada',
            nombreEtoiles: 5,
            nombreChambres: 310,
            image: "https://cf.bstatic.com/images/hotel/max1024x768/967/96725900.jpg",
            caracteristiques: [ 'Gardiennage', 
                                'Chasseur ',
                                "Stationnement",
                                "Location de voitures de luxe",
                                "Les chambres comprennent un téléphone sans fil à deux lignes, une salle de bain luxueuse, des articles de toilette de luxe et un coffret de sécurité",
                                "Accès gratuit à Internet haute vitesse sans fil", 
                                'Séchoir à cheveux',
                                "PMinibar (des frais s'appliquent)", 
                                'Cafetière Nespresso Vertuoline'],
        },
        dateDepart:  "2021-01-01",
        dateRetour: "2021-01-15",
        prix: 800,
        rabais: 120,
        vedette: false
    },
    {
        _id: '',
        da:'République dominicaine',
        destination: 'Punta Cana, République dominicaine',
        villeDepart: 'Toronto',
        hotel: {
            nom: 'Tortuga Bay Hotel Puntacana Resort & Club',
            coordonnees: 'Punta Cana, La Altagracia',
            nombreEtoiles: 3,
            nombreChambres: 310,
            image: "https://static-new.lhw.com/HotelImages/Final/LW1921/lw1921_28054897_720x450.jpg" ,
            caracteristiques: [ 'Un magnifique spa Six Senses avec des massages et des soins de salon', 
                                'Toutes les suites comprennent des vélos de randonnée et une voiture de golf privée',
                                "Le Wi-Fi gratuit et un service de voiturier",
                                "La boutique vend des articles Oscar de la Renta",
                                "Bar de la piscine",
                                "Service boissons au bord de la piscine", 
                                'Terrain de golf',
                                "Laverie", 
                                'Centre de conditionnement physique'],
        },
        dateDepart:  "2021-01-01",
        dateRetour: "2021-01-15",
        prix: 810,
        rabais: 70,
        vedette: false
    },
    {
        _id: '',
        da:'République dominicaine',
        destination: 'République Dominicaine',
        villeDepart: 'Toronto',
        hotel: {
            nom: 'El Embajador',
            coordonnees: ' Sarasota, 65, Saint-Domingue, République dominicainee',
            nombreEtoiles: 5,
            nombreChambres: 450,
            image: "https://www.colonialtours.com/images/Occidental-El-Embajador-1A.jpg",
            caracteristiques: [ 'Les restaurants et bars de l’hôtel proposent une offre gastronomique variée', 
                                'Bi Wellness & Spa',
                                " Forfaits les lunes de miel",
                                "Renouvellement des vœux",
                                "Connexion wifi (gratuit)",
                                "Cafetière/Théière", 
                                'Vue sur la mer',
                                "Plage", 
                                "Excellente services avec luxueuses installations"],
        },
        dateDepart:  "2021-01-01",
        dateRetour: "2021-01-15",
        prix: 580,
        rabais: 65,
        vedette: true
    },
    {
        _id: '',
        da: 'Martinique',
        destination: 'Martinique',
        villeDepart: 'Toronto',
        hotel: {
            nom: 'Hotel Pelican',
            coordonnees: '13 bis Rue Joseph Shymphor Schoelcher, 97233, Martinique',
            nombreEtoiles: 3,
            nombreChambres: 325,
            image: "https://cf.bstatic.com/images/hotel/max1024x768/201/201804557.jpg",
            caracteristiques: [ 'Chambres meublées climatisées', 
                                'Piscinel',
                                "Vue Mer",
                                "Parking",
                                "2 piscines",
                                "Cafetière/Théière",
                                "Le Wi-Fi gratuit et un service de voiturier",
                                "2 pisTransferts aéroport aller-retour",],
                            },
                            dateDepart:  "2021-01-01",
                            dateRetour: "2021-01-15",
        prix: 250,
        rabais: 35,
        vedette: true
    },
];